--------------------------------------------------------------------------------
-- Up
--------------------------------------------------------------------------------

CREATE TABLE users (
  id         INTEGER   PRIMARY KEY, -- user's ID, autogenerated
  username      TEXT NOT NULL,  -- user's email
  password   TEXT NOT NULL,  -- password
  f_name     TEXT,  -- user's first name
  l_name     TEXT,  -- user's first name
  bio        TEXT  -- user's bio
);

CREATE TABLE Follows (
  user_id        INTEGER   NOT NULL, -- equal to a user's ID
  followed       INTEGER   NOT NULL -- followed user id
);


CREATE TABLE Posts (
  id             INTEGER   PRIMARY KEY AUTOINCREMENT, -- a given post's id, autogenerated
  user_id        INTEGER   NOT NULL, -- equal to a user's ID
  description    TEXT      NOT NULL, -- text field for post
  url            TEXT      NOT NULL, -- url to image hosted externally
  likes          INTEGER
);

--------------------------------------------------------------------------------
-- Down
--------------------------------------------------------------------------------

INSERT INTO users (id, username, password) VALUES ('aaron', 'aaron@cohen', 'password');

INSERT INTO users (id, username, password) VALUES ('kirsi', 'kirsi@ceballos', 'password');

INSERT INTO users (id, username, password) VALUES ('max', 'max@osm', 'password');

INSERT INTO users (id, username, password) VALUES ('default_user', 'user@email', 'password');

INSERT INTO Follows (user_id, followed) VALUES (1,2);

INSERT INTO Follows (user_id, followed) VALUES (2,3);

INSERT INTO Follows (user_id, followed) VALUES (3,1);

INSERT INTO Follows (user_id, followed) VALUES (4,1);

INSERT INTO Posts (id, user_id, description, url) VALUES (1, 'url', 'https://c1.staticflickr.com/8/7693/17123251389_bed3c3a1ba_b.jpg');

INSERT INTO Posts (id, user_id, description, url) VALUES (1, 'text', 'this is a post');

INSERT INTO Posts (id, user_id, description, url) VALUES (2, 'url', 'http://imgur.com/gallery/pqGR8D6');

INSERT INTO Posts (id, user_id, description, url) VALUES (3, 'text', 'another post');

INSERT INTO Posts (id, user_id, description, url) VALUES (4, 'text', 'another post');

DROP TABLE users;
DROP TABLE Follows;
DROP TABLE Posts;
